python scripts/supabase_data.py --tables components
python scripts/supabase_data.py --tables radicals
python scripts/supabase_data.py --tables chars
python scripts/supabase_data.py --tables words
python scripts/supabase_data.py --tables phrases
python scripts/supabase_data.py --tables component_char
python scripts/supabase_data.py --tables char_word
python scripts/supabase_data.py --tables word_phrase
python scripts/supabase_data.py --tables slang
